name: Packer Build

on: 
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: check_format
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Packer
      run: sudo apt-get update && sudo apt-get install -y packer 
    - name: Check Packer file format
      run: |
          if ! packer fmt -check packer; then
             echo "Packer format is not correct. Please run 'packer fmt' to fix the issue."
             exit 1
          fi
    - name: Check packer file is valid
      run: |
           packer init packer
           if ! packer validate packer; then
             echo "Packer files are not valid"
             exit 1
           fi
